name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Railway
        run: bash <(curl -fsSL cli.new)

      - name: Link to the environment
        run: railway environment staging
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}

      - name: Deploy
        run: railway up -ci --service fastify-webapp-sample
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}
